language: cpp

compiler:
  - clang
  - gcc

env:
  global:
    - LUAROCKS_VER=2.2.2
    - LUA_VER=5.1.5
    - COMPILE_LUA=no

matrix:
  include:
    - compiler: gcc
      env: COMPILE_LUA=yes

sudo: false

addons:
  apt:
    packages:
    - lua5.1
    - liblua5.1-0-dev
    - libboost-dev
    - libboost-system-dev
    - libboost-date-time-dev
    - libboost-thread-dev

before_install:
  - export LUA_SHORTV="$(echo $LUA_VER | cut -c 1-3)"
  - mkdir -p "$HOME/build_deps"
  - source ci/travis/set_env.sh
  - ci/travis/install_lua.sh
  - ci/travis/install_luarocks.sh
  - eval `luarocks path`
  #
  # Report versions
  - lua -v
  - luarocks --version
  #
  # install dependencies
  - luarocks install lunit
  #

install:
  - ci/travis/build.sh
  - export PATH=$PATH:${TRAVIS_BUILD_DIR}/build
  - luanode -v

script:
  - cd $TRAVIS_BUILD_DIR/test
  - ./run.sh
