language: cpp

compiler:
  - clang
  - gcc

env:
  global:
    - LUAROCKS_VER=2.2.2
    - LUA_VER=5.1.5
    - COMPILE_LUA=no

matrix:
  include:
    - compiler: gcc
      - COMPILE_LUA=yes

sudo: false

addons:
  apt:
    packages:
    - lua5.1
    - liblua5.1-0-dev
    - libboost-dev
    - libboost-system-dev
    - libboost-date-time-dev
    - libboost-thread-dev

before_install:
  - export LUA_SHORTV="$(echo $LUA_VER | cut -c 1-3)"
  - mkdir -p "$HOME/build_deps"
  - ci/travis/install_lua.sh
  - ci/travis/install_luarocks.sh
  #
  # install dependencies
  - luarocks install lunit
  #

install:
  - lua -v
  - luarocks --version
  - cd $TRAVIS_BUILD_DIR/build
  - cmake -DBOOST_ROOT=/usr/lib ..
  - cmake --build .
  - cp luanode luanode_d
  - export PATH=$PATH:$(pwd)
  - eval `luarocks path`
  - luanode -v

script:
  - cd $TRAVIS_BUILD_DIR/test
  - ./run.sh
