version: 0.0.2.{build}

os: Windows Server 2012 R2

shallow_clone: true

environment:
  LUAURL: http://www.lua.org/ftp
  LUA_VER: 5.1.5
  LUA_SHORTV: 5.1
  LUA_SHORTVND: 51
  ARTIFACTS: c:\artifacts

  matrix:
  - platform: x86
  #- platform: x64  # disabled until I figure out why it does not compile

matrix:
  fast_finish: false     # set this flag to true to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x64

init:
# Make VS 2013 command line tools available
- '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%'
# Create 'artifacts' folder
- md %ARTIFACTS%

install:
- cd %APPVEYOR_BUILD_FOLDER%
- call ci\appveyor\install.bat

build_script:
- cd %APPVEYOR_BUILD_FOLDER%
- call ci\appveyor\build.bat

test_script:
- cd %APPVEYOR_BUILD_FOLDER%\test
- set PATH=C:\OpenSSL-Win32\bin;%PATH%
- runappveyor.cmd
